# Sentinel-X — Mosquitto PRODUCTION : TLS uniquement (8883)
per_listener_settings false
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/aclfile

persistence true
persistence_location /mosquitto/data/

# Journaux sur stdout : rotation gérée par Docker (10 Mo x 3)
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp_format %Y-%m-%dT%H:%M:%S

listener 8883
protocol mqtt
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
