# Sentinel-X — Mosquitto DÉVELOPPEMENT (lundi) : 1883 en clair, MAIS authentifié
per_listener_settings false
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/aclfile

persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all
connection_messages true

listener 1883
protocol mqtt
